version: "3.9"

services:
  postgres:
    container_name: postgres_cont
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
networks:
  postgres:
    driver: bridge

volumes:
  postgres: