# Generated by Django 4.1.3 on 2023-05-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Iha',
        ),
    ]
